#!/bin/bash
echo "This script simply documents how to clone a drive via Linux."
echo "This has been tested on a standard build of Kali as well."
echo ""
echo "Discovery"
echo "---------"
echo "fdisk -l [Find the source and destination disks]"
echo "fdisk -l -u /dev/<source disk> [Need the start and end sectors]"
echo ""
echo "Partitioning new drive"
echo "----------------------"
echo "fdisk /dev/<destination disk>"
echo "    use 'p' to view partition table"
echo "    You can use 'u' to toggle sector/cylinder mode but the new default is sectors so you shouldn't have to."
echo "    use 'n' for new partition. (Select 'p' - primary and a #.  Partition #'s should match or the windows boot may not work)"
echo "    use the start and last sectors from the fdisk -l -u for each partition"
echo "    Set the boot flag for the appropriate partition using 'a' then the partition number (you'll see this with an * in the fdisk listing)"
echo "    Use 't' to set the partition type for each partition.  Hex code '7' is HPFS/NTFS"
echo "    Once done you can see the status with 'p' to view the partition then use 'w' to write the changes to disk."
echo ""
echo "Copying the data"
echo "-----------------"
echo "Copy the MBR:  dd if=/dev/<source: e.g. sda> of=/dev/<dest: e.g. sdb> bs=446 count=1"
echo "Optional: enable DMA on both disks to increase speed: hdparm -d 1 /dev/<disk>"
echo "Use ntfsclone to copy data for each NTFS partition.  CAUTION: watch the source dest parameters, they're backwards."
echo "ntfsclone --overwrite <destination> <source>"
echo "  example: ntfsclone --overwrite /dev/sdb1 /dev/sda1"
echo "If it's not NTFS, can just use dd:"
echo "dd if=/dev/sda1 of=/dev/sdb1 bs=4096  (verify block size before running)"
echo "If the disk has bad sectors you should use ddrescue instead of dd"
echo ""
echo "Resizing if newer drive is bigger"
echo "---------------------------------"
echo "Use gparted to resize."
echo ""

