#!/bin/sh

if [ $# -eq 0 ]; then
	echo "Usage: $0 <input PEM file> <output DER file>"
	echo "$0 converts a PEM file generated by a certificate issuer into a DER file."
	echo ""
	exit 1
fi

PEMFILE=$1
DERFILE=$2

openssl x509 -in $PEMFILE -outform der -out $DERFILE

if [ $? -gt 0 ]; then
	echo "ERROR!  Terminating."
	exit 2
fi
