#!/bin/sh

if [ $# -eq 0 ]; then
	echo "Usage: $0 <input crt file> <output PEM file> [private key file]"
	echo "$0 converts a crt file generated by a certificate issuer into a PEM file."
	echo "Note: PEM files contain both the certificate and the private key so the issuer"
	echo "e.g. GoDaddy does not include the private key.  This must simply be appended to the"
	echo "PEM after conversion."
	echo ""
	exit 1
fi

CRTFILE=$1
PEMFILE=$2
KEYFILE=""

openssl x509 -in $CRTFILE -out $PEMFILE

if [ $? -gt 0 ]; then
	echo "ERROR!  Terminating."
	exit 2
fi

if [ $# -gt 2 ]; then
	KEYFILE=$3

	cat $KEYFILE >> $PEMFILE
fi

